(* font_data.sml -- GENERATED by tools/embed_font.py; do not edit by hand.

   The bundled 5x7 BDF font (data/font5x7.bdf) baked in as a string so that
   Plot.render is self-contained and parses the font at module load with no
   file I/O. *)

structure FontData =
struct
  val bdf =
    "STARTFONT 2.1\n\
    \FONT -sjqtentacles-font5x7-medium-r-normal--7-70-75-75-c-50-iso10646-1\n\
    \SIZE 7 75 75\n\
    \FONTBOUNDINGBOX 5 7 0 0\n\
    \STARTPROPERTIES 5\n\
    \FONT_ASCENT 7\n\
    \FONT_DESCENT 0\n\
    \DEFAULT_CHAR 63\n\
    \PIXEL_SIZE 7\n\
    \POINT_SIZE 70\n\
    \ENDPROPERTIES\n\
    \CHARS 91\n\
    \STARTCHAR space\n\
    \ENCODING 32\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \ENDCHAR\n\
    \STARTCHAR char65\n\
    \ENCODING 65\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \88\n\
    \F8\n\
    \88\n\
    \88\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char66\n\
    \ENCODING 66\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F0\n\
    \88\n\
    \88\n\
    \F0\n\
    \88\n\
    \88\n\
    \F0\n\
    \ENDCHAR\n\
    \STARTCHAR char67\n\
    \ENCODING 67\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \80\n\
    \80\n\
    \80\n\
    \88\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char68\n\
    \ENCODING 68\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F0\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \F0\n\
    \ENDCHAR\n\
    \STARTCHAR char69\n\
    \ENCODING 69\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F8\n\
    \80\n\
    \80\n\
    \F0\n\
    \80\n\
    \80\n\
    \F8\n\
    \ENDCHAR\n\
    \STARTCHAR char70\n\
    \ENCODING 70\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F8\n\
    \80\n\
    \80\n\
    \F0\n\
    \80\n\
    \80\n\
    \80\n\
    \ENDCHAR\n\
    \STARTCHAR char71\n\
    \ENCODING 71\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \80\n\
    \B8\n\
    \88\n\
    \88\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char72\n\
    \ENCODING 72\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \88\n\
    \88\n\
    \88\n\
    \F8\n\
    \88\n\
    \88\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char73\n\
    \ENCODING 73\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F8\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \F8\n\
    \ENDCHAR\n\
    \STARTCHAR char74\n\
    \ENCODING 74\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \38\n\
    \10\n\
    \10\n\
    \10\n\
    \10\n\
    \90\n\
    \60\n\
    \ENDCHAR\n\
    \STARTCHAR char75\n\
    \ENCODING 75\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \88\n\
    \90\n\
    \A0\n\
    \C0\n\
    \A0\n\
    \90\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char76\n\
    \ENCODING 76\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \80\n\
    \80\n\
    \80\n\
    \80\n\
    \80\n\
    \80\n\
    \F8\n\
    \ENDCHAR\n\
    \STARTCHAR char77\n\
    \ENCODING 77\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \88\n\
    \D8\n\
    \A8\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char78\n\
    \ENCODING 78\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \88\n\
    \C8\n\
    \A8\n\
    \98\n\
    \88\n\
    \88\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char79\n\
    \ENCODING 79\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char80\n\
    \ENCODING 80\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F0\n\
    \88\n\
    \88\n\
    \F0\n\
    \80\n\
    \80\n\
    \80\n\
    \ENDCHAR\n\
    \STARTCHAR char81\n\
    \ENCODING 81\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \88\n\
    \88\n\
    \A8\n\
    \90\n\
    \68\n\
    \ENDCHAR\n\
    \STARTCHAR char82\n\
    \ENCODING 82\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F0\n\
    \88\n\
    \88\n\
    \F0\n\
    \A0\n\
    \90\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char83\n\
    \ENCODING 83\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \78\n\
    \80\n\
    \80\n\
    \70\n\
    \08\n\
    \08\n\
    \F0\n\
    \ENDCHAR\n\
    \STARTCHAR char84\n\
    \ENCODING 84\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F8\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \ENDCHAR\n\
    \STARTCHAR char85\n\
    \ENCODING 85\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char86\n\
    \ENCODING 86\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \50\n\
    \20\n\
    \ENDCHAR\n\
    \STARTCHAR char87\n\
    \ENCODING 87\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \88\n\
    \88\n\
    \88\n\
    \A8\n\
    \A8\n\
    \D8\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char88\n\
    \ENCODING 88\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \88\n\
    \88\n\
    \50\n\
    \20\n\
    \50\n\
    \88\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char89\n\
    \ENCODING 89\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \88\n\
    \88\n\
    \50\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \ENDCHAR\n\
    \STARTCHAR char90\n\
    \ENCODING 90\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F8\n\
    \08\n\
    \10\n\
    \20\n\
    \40\n\
    \80\n\
    \F8\n\
    \ENDCHAR\n\
    \STARTCHAR char97\n\
    \ENCODING 97\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \70\n\
    \08\n\
    \78\n\
    \88\n\
    \78\n\
    \ENDCHAR\n\
    \STARTCHAR char98\n\
    \ENCODING 98\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \80\n\
    \80\n\
    \F0\n\
    \88\n\
    \88\n\
    \88\n\
    \F0\n\
    \ENDCHAR\n\
    \STARTCHAR char99\n\
    \ENCODING 99\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \78\n\
    \80\n\
    \80\n\
    \80\n\
    \78\n\
    \ENDCHAR\n\
    \STARTCHAR char100\n\
    \ENCODING 100\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \08\n\
    \08\n\
    \78\n\
    \88\n\
    \88\n\
    \88\n\
    \78\n\
    \ENDCHAR\n\
    \STARTCHAR char101\n\
    \ENCODING 101\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \70\n\
    \88\n\
    \F8\n\
    \80\n\
    \78\n\
    \ENDCHAR\n\
    \STARTCHAR char102\n\
    \ENCODING 102\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \30\n\
    \48\n\
    \40\n\
    \E0\n\
    \40\n\
    \40\n\
    \40\n\
    \ENDCHAR\n\
    \STARTCHAR char103\n\
    \ENCODING 103\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \78\n\
    \88\n\
    \88\n\
    \78\n\
    \08\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char104\n\
    \ENCODING 104\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \80\n\
    \80\n\
    \F0\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char105\n\
    \ENCODING 105\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \20\n\
    \00\n\
    \60\n\
    \20\n\
    \20\n\
    \20\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char106\n\
    \ENCODING 106\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \10\n\
    \00\n\
    \30\n\
    \10\n\
    \10\n\
    \90\n\
    \60\n\
    \ENDCHAR\n\
    \STARTCHAR char107\n\
    \ENCODING 107\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \80\n\
    \80\n\
    \90\n\
    \A0\n\
    \C0\n\
    \A0\n\
    \90\n\
    \ENDCHAR\n\
    \STARTCHAR char108\n\
    \ENCODING 108\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \60\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char109\n\
    \ENCODING 109\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \D0\n\
    \A8\n\
    \A8\n\
    \88\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char110\n\
    \ENCODING 110\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \F0\n\
    \88\n\
    \88\n\
    \88\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char111\n\
    \ENCODING 111\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \70\n\
    \88\n\
    \88\n\
    \88\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char112\n\
    \ENCODING 112\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \F0\n\
    \88\n\
    \88\n\
    \F0\n\
    \80\n\
    \80\n\
    \ENDCHAR\n\
    \STARTCHAR char113\n\
    \ENCODING 113\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \78\n\
    \88\n\
    \88\n\
    \78\n\
    \08\n\
    \08\n\
    \ENDCHAR\n\
    \STARTCHAR char114\n\
    \ENCODING 114\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \B0\n\
    \C8\n\
    \80\n\
    \80\n\
    \80\n\
    \ENDCHAR\n\
    \STARTCHAR char115\n\
    \ENCODING 115\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \78\n\
    \80\n\
    \70\n\
    \08\n\
    \F0\n\
    \ENDCHAR\n\
    \STARTCHAR char116\n\
    \ENCODING 116\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \40\n\
    \40\n\
    \E0\n\
    \40\n\
    \40\n\
    \48\n\
    \30\n\
    \ENDCHAR\n\
    \STARTCHAR char117\n\
    \ENCODING 117\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \88\n\
    \88\n\
    \88\n\
    \98\n\
    \68\n\
    \ENDCHAR\n\
    \STARTCHAR char118\n\
    \ENCODING 118\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \88\n\
    \88\n\
    \88\n\
    \50\n\
    \20\n\
    \ENDCHAR\n\
    \STARTCHAR char119\n\
    \ENCODING 119\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \88\n\
    \88\n\
    \A8\n\
    \A8\n\
    \50\n\
    \ENDCHAR\n\
    \STARTCHAR char120\n\
    \ENCODING 120\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \88\n\
    \50\n\
    \20\n\
    \50\n\
    \88\n\
    \ENDCHAR\n\
    \STARTCHAR char121\n\
    \ENCODING 121\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \88\n\
    \88\n\
    \88\n\
    \78\n\
    \08\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char122\n\
    \ENCODING 122\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \F8\n\
    \10\n\
    \20\n\
    \40\n\
    \F8\n\
    \ENDCHAR\n\
    \STARTCHAR char48\n\
    \ENCODING 48\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \98\n\
    \50\n\
    \C8\n\
    \88\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char49\n\
    \ENCODING 49\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \20\n\
    \60\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char50\n\
    \ENCODING 50\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \08\n\
    \10\n\
    \20\n\
    \40\n\
    \F8\n\
    \ENDCHAR\n\
    \STARTCHAR char51\n\
    \ENCODING 51\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F8\n\
    \10\n\
    \20\n\
    \10\n\
    \08\n\
    \88\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char52\n\
    \ENCODING 52\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \10\n\
    \30\n\
    \50\n\
    \90\n\
    \F8\n\
    \10\n\
    \10\n\
    \ENDCHAR\n\
    \STARTCHAR char53\n\
    \ENCODING 53\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F8\n\
    \80\n\
    \F0\n\
    \08\n\
    \08\n\
    \88\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char54\n\
    \ENCODING 54\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \30\n\
    \40\n\
    \80\n\
    \F0\n\
    \88\n\
    \88\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char55\n\
    \ENCODING 55\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \F8\n\
    \08\n\
    \10\n\
    \20\n\
    \40\n\
    \40\n\
    \40\n\
    \ENDCHAR\n\
    \STARTCHAR char56\n\
    \ENCODING 56\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \88\n\
    \70\n\
    \88\n\
    \88\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char57\n\
    \ENCODING 57\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \88\n\
    \78\n\
    \08\n\
    \10\n\
    \60\n\
    \ENDCHAR\n\
    \STARTCHAR char46\n\
    \ENCODING 46\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \60\n\
    \60\n\
    \ENDCHAR\n\
    \STARTCHAR char44\n\
    \ENCODING 44\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \60\n\
    \20\n\
    \40\n\
    \ENDCHAR\n\
    \STARTCHAR char58\n\
    \ENCODING 58\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \60\n\
    \60\n\
    \00\n\
    \60\n\
    \60\n\
    \00\n\
    \ENDCHAR\n\
    \STARTCHAR char59\n\
    \ENCODING 59\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \60\n\
    \60\n\
    \00\n\
    \60\n\
    \20\n\
    \40\n\
    \ENDCHAR\n\
    \STARTCHAR char33\n\
    \ENCODING 33\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \00\n\
    \20\n\
    \ENDCHAR\n\
    \STARTCHAR char63\n\
    \ENCODING 63\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \08\n\
    \10\n\
    \20\n\
    \00\n\
    \20\n\
    \ENDCHAR\n\
    \STARTCHAR char45\n\
    \ENCODING 45\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \00\n\
    \F8\n\
    \00\n\
    \00\n\
    \00\n\
    \ENDCHAR\n\
    \STARTCHAR char43\n\
    \ENCODING 43\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \20\n\
    \20\n\
    \F8\n\
    \20\n\
    \20\n\
    \00\n\
    \ENDCHAR\n\
    \STARTCHAR char61\n\
    \ENCODING 61\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \F8\n\
    \00\n\
    \F8\n\
    \00\n\
    \00\n\
    \ENDCHAR\n\
    \STARTCHAR char42\n\
    \ENCODING 42\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \88\n\
    \50\n\
    \F8\n\
    \50\n\
    \88\n\
    \00\n\
    \ENDCHAR\n\
    \STARTCHAR char47\n\
    \ENCODING 47\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \08\n\
    \08\n\
    \10\n\
    \20\n\
    \40\n\
    \80\n\
    \80\n\
    \ENDCHAR\n\
    \STARTCHAR char92\n\
    \ENCODING 92\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \80\n\
    \80\n\
    \40\n\
    \20\n\
    \10\n\
    \08\n\
    \08\n\
    \ENDCHAR\n\
    \STARTCHAR char95\n\
    \ENCODING 95\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \F8\n\
    \ENDCHAR\n\
    \STARTCHAR char124\n\
    \ENCODING 124\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \20\n\
    \ENDCHAR\n\
    \STARTCHAR char40\n\
    \ENCODING 40\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \10\n\
    \20\n\
    \40\n\
    \40\n\
    \40\n\
    \20\n\
    \10\n\
    \ENDCHAR\n\
    \STARTCHAR char41\n\
    \ENCODING 41\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \40\n\
    \20\n\
    \10\n\
    \10\n\
    \10\n\
    \20\n\
    \40\n\
    \ENDCHAR\n\
    \STARTCHAR char91\n\
    \ENCODING 91\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \40\n\
    \40\n\
    \40\n\
    \40\n\
    \40\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char93\n\
    \ENCODING 93\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \10\n\
    \10\n\
    \10\n\
    \10\n\
    \10\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char123\n\
    \ENCODING 123\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \18\n\
    \20\n\
    \20\n\
    \40\n\
    \20\n\
    \20\n\
    \18\n\
    \ENDCHAR\n\
    \STARTCHAR char125\n\
    \ENCODING 125\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \C0\n\
    \20\n\
    \20\n\
    \10\n\
    \20\n\
    \20\n\
    \C0\n\
    \ENDCHAR\n\
    \STARTCHAR char60\n\
    \ENCODING 60\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \10\n\
    \20\n\
    \40\n\
    \80\n\
    \40\n\
    \20\n\
    \10\n\
    \ENDCHAR\n\
    \STARTCHAR char62\n\
    \ENCODING 62\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \40\n\
    \20\n\
    \10\n\
    \08\n\
    \10\n\
    \20\n\
    \40\n\
    \ENDCHAR\n\
    \STARTCHAR char35\n\
    \ENCODING 35\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \50\n\
    \F8\n\
    \50\n\
    \F8\n\
    \50\n\
    \00\n\
    \00\n\
    \ENDCHAR\n\
    \STARTCHAR char34\n\
    \ENCODING 34\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \50\n\
    \50\n\
    \50\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \ENDCHAR\n\
    \STARTCHAR char39\n\
    \ENCODING 39\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \20\n\
    \20\n\
    \20\n\
    \00\n\
    \00\n\
    \00\n\
    \00\n\
    \ENDCHAR\n\
    \STARTCHAR char64\n\
    \ENCODING 64\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \70\n\
    \88\n\
    \B8\n\
    \A8\n\
    \B8\n\
    \80\n\
    \70\n\
    \ENDCHAR\n\
    \STARTCHAR char37\n\
    \ENCODING 37\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \C0\n\
    \C8\n\
    \10\n\
    \20\n\
    \40\n\
    \98\n\
    \18\n\
    \ENDCHAR\n\
    \STARTCHAR char38\n\
    \ENCODING 38\n\
    \SWIDTH 480 0\n\
    \DWIDTH 6 0\n\
    \BBX 5 7 0 0\n\
    \BITMAP\n\
    \60\n\
    \90\n\
    \90\n\
    \60\n\
    \98\n\
    \90\n\
    \68\n\
    \ENDCHAR\n\
    \ENDFONT\n"
end
